#!/bin/bash

# To be used on data files generated by Ulmer's code (branch: `ippl-orig`)
# Removes all artefacts that inhibit reading it as a proper CSV file

# Remove all whitespaces and replace trailing comma
find $1 -type f -name '*.csv' -exec sed -i -z 's/\ //g;s/)\n/\n/g' {} +
# Remove all parentheses and replace with commas
find $1 -type f -name '*.csv' -exec sed -i 's/)(/,/g;s/(/,/g;s/)/,/g' {} +